default: &default
  adapter: postgresql
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  post: 5432

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "backend2_development" %>

test:
  <<: *default
  database: backend2_test

production:
  primary: &primary_production
    <<: *default
    database: backend_production
  cache:
    <<: *primary_production
    database: backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: backend_production_cable
    migrations_paths: db/cable_migrate
